services:
    grebi-dataload:
      build:
        context: .
        dockerfile: Dockerfile.dataload
      environment:
        - GREBI_NFS_TMP=/work/tmp
        - GREBI_HPS_TMP=/work/tmp
        - GREBI_CONFIG=${GREBI_CONFIG:?}
      command: bash -c "cd /work && ./scripts/run_pipeline_local.sh"
    grebi-neo4j:
      image: neo4j:5.18.0
      ports:
        - 7474:7474
        - 7687:7687
      volumes:
        - grebi-neo4j-data:/var/lib/neo4j/data
      environment:
        - NEO4J_AUTH=none
      depends_on:
        grebi-dataload:
          condition: service_completed_successfully
    # grebi-api:
    #   build: ./grebi_api
    #   ports:
    #     - 8080:8080
    #   environment:
    #     - GREBI_NEO4J_HOST=bolt://grebi-neo4j:7687
    #   depends_on:
    #     - grebi-neo4j    
    #   links:
    #     - grebi-neo4j 
    # grebi-ui:
    #   build:
    #     context: ./grebi_ui
    #   #env_file: ./grebi_ui/.env
    #   ports:
    #     - 8081:8080
    #   depends_on:
    #     - grebi-api
    #   links:
    #     - grebi-api
volumes:
    grebi-neo4j-data:


