<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>uk.ac.ebi</groupId>
    <artifactId>grebi-parent</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>grebi-parent</name>

    <modules>
        <module>webapp/grebi_api</module>
        <module>webapp/grebi_metadata_service</module>
        <module>webapp/grebi_resolver_service</module>
        <module>webapp/grebi_cypher_service</module>
    </modules>
</project>
