
from shared import config

config['id'] = 'EBI_MONARCH'
config['name'] = 'EBI Resources and MONARCH Initiative KG'
config['datasource_configs'] = [
    "./configs/datasource_configs/gwas.yaml",
    "./configs/datasource_configs/hgnc.yaml",
    "./configs/datasource_configs/impc.yaml",
    "./configs/datasource_configs/sssom.yaml",
    # OLS ontologies (split for parallel processing)
    "./configs/datasource_configs/ols/ols_efo.yaml",
    "./configs/datasource_configs/ols/ols_mp.yaml",
    "./configs/datasource_configs/ols/ols_hp.yaml",
    "./configs/datasource_configs/ols/ols_go.yaml",
    "./configs/datasource_configs/ols/ols_ro.yaml",
    "./configs/datasource_configs/ols/ols_iao.yaml",
    "./configs/datasource_configs/ols/ols_uberon.yaml",
    "./configs/datasource_configs/ols/ols_pato.yaml",
    "./configs/datasource_configs/ols/ols_oba.yaml",
    "./configs/datasource_configs/ols/ols_chebi.yaml",
    "./configs/datasource_configs/ols/ols_bspo.yaml",
    "./configs/datasource_configs/ols/ols_obi.yaml",
    "./configs/datasource_configs/ols/ols_bfo.yaml",
    "./configs/datasource_configs/ols/ols_cob.yaml",
    "./configs/datasource_configs/ols/ols_cl.yaml",
    "./configs/datasource_configs/ols/ols_so.yaml",
    "./configs/datasource_configs/ols/ols_eco.yaml",
    "./configs/datasource_configs/ols/ols_pr.yaml",
    "./configs/datasource_configs/ols/ols_ncbitaxon.yaml",
    "./configs/datasource_configs/ols/ols_oio.yaml",
    "./configs/datasource_configs/ols/ols_biolink.yaml",
    "./configs/datasource_configs/ols/ols_mondo.yaml",
    "./configs/datasource_configs/ols/ols_doid.yaml",
    "./configs/datasource_configs/ols/ols_cheminf.yaml",
    "./configs/datasource_configs/ols/ols_dc.yaml",
    "./configs/datasource_configs/ols/ols_dcterms.yaml",
    "./configs/datasource_configs/ols/ols_ncit.yaml",
    "./configs/datasource_configs/ols/ols_edam.yaml",
    "./configs/datasource_configs/ols/ols_upheno.yaml",
    "./configs/datasource_configs/ols/ols_ecto.yaml",
    "./configs/datasource_configs/reactome.yaml",
    "./configs/datasource_configs/ubergraph.yaml",
    "./configs/datasource_configs/otar/otar_evidence.yaml",
    "./configs/datasource_configs/otar/otar_drug_indication.yaml",
    "./configs/datasource_configs/otar/otar_drug_molecule.yaml",
    "./configs/datasource_configs/otar/otar_disease_phenotype.yaml",
    "./configs/datasource_configs/monarch.yaml",
    "./configs/datasource_configs/metabolights.yaml",
    "./configs/datasource_configs/mondo_efo.yaml",
    "./configs/datasource_configs/ctd.yaml",
    "./configs/datasource_configs/mgnify.yaml",
    "./configs/datasource_configs/hett_pesticides/hett_pesticides_appril.yaml",
    "./configs/datasource_configs/hett_pesticides/hett_pesticides_eu.yaml",
    "./configs/datasource_configs/hett_pesticides/hett_pesticides_gb.yaml",
    "./configs/datasource_configs/aopwiki.yaml",
    "./configs/datasource_configs/chembl.yaml",
    "./configs/datasource_configs/robokop/robokop_alliance.yaml",
    "./configs/datasource_configs/robokop/robokop_binding.yaml",
    "./configs/datasource_configs/robokop/robokop_cam.yaml",
    "./configs/datasource_configs/robokop/robokop_drugcentral.yaml",
    "./configs/datasource_configs/robokop/robokop_gtex.yaml",
    "./configs/datasource_configs/robokop/robokop_gtopdb.yaml",
    "./configs/datasource_configs/robokop/robokop_hetionet.yaml",
    "./configs/datasource_configs/robokop/robokop_hgoa.yaml",
    "./configs/datasource_configs/robokop/robokop_hmdb.yaml",
    "./configs/datasource_configs/robokop/robokop_icees.yaml",
    "./configs/datasource_configs/robokop/robokop_intact.yaml",
    "./configs/datasource_configs/robokop/robokop_panther.yaml",
    "./configs/datasource_configs/robokop/robokop_pharos.yaml",
    "./configs/datasource_configs/robokop/robokop_string.yaml",
    "./configs/datasource_configs/robokop/robokop_textmining.yaml",
    "./configs/datasource_configs/robokop/robokop_viralproteome.yaml",
    "./configs/datasource_configs/mesh.yaml",
    "./configs/datasource_configs/primekg.yaml",
    "./configs/datasource_configs/ols_top_k.yaml",
    "./configs/datasource_configs/dismech.yaml"
]

if __name__ == '__main__':
    import json
    print(json.dumps(config, indent=2))

