use grebi_golden::GoldenCase;

/// Linked nodes, edges and graph metadata of the clique-merge test subgraph, as the pipeline recorded them.
#[test]
fn links_the_merged_entities_into_nodes_and_edges() {
    GoldenCase::new(env!("CARGO_BIN_EXE_grebi_link"), "tests/golden/test_clique_merge")
        .args(["--in-metadata-jsonl", "$CASE/entity_metadata.jsonl", "--in-graph-metadata-json", "$CASE/graph_metadata.json", "--groups-txt", "$CASE/groups.txt", "--out-edges-jsonl", "linked_edges_test_clique_merge_000000.jsonl", "--out-graph-metadata-json", "linked_graph_metadata_test_clique_merge_000000.json", "--exclude", "id,owl:equivalentClass,owl:equivalentProperty,owl:sameAs,grebi:hashId,grebi:equivalentTo,ols:iri,ols:shortForm,hgnc:ensembl_gene_id,obo:chebi/inchi,obo:chebi/inchikey,obo:chebi/smiles,otar:canonicalSmiles,otar:inchiKey,impc:pmId,impc:humanGeneAccId,monarch:iri,skos:exactMatch,ncit:P368,ncit:C98965,dcterms:identifier,oboinowl:hasAlternativeId,robokop:equivalent_identifiers,mesh.vocab:identifier", "--exclude-self-referential", "foaf:page,rdfs:seeAlso,oboinowl:hasDbXref,biolink:subclass_of,biolink:broad_match,ols:ontology_purl,ols:ontologyId,cheminf:000407,cheminf:InChIKey,biolink:interacts_with,reactome:url,dc:Identifier,hgnc:agr,hgnc:gencc,monarch:xref,hgnc:uniprot_ids,hgnc:omim_id,hgnc:entrez_id,reactome:referenceGene,reactome:identifier,reactome:crossReference,edam:Ensembl_gene_id,obo:pr#has_gene_template,ols:relatedTo,ols:relatedFrom,robokop:smiles,ctd:ChemicalURL,ctd:UniProtIDs,ols:linksTo,id,owl:equivalentClass,owl:equivalentProperty,owl:sameAs,grebi:hashId,grebi:equivalentTo,ols:iri,ols:shortForm,hgnc:ensembl_gene_id,obo:chebi/inchi,obo:chebi/inchikey,obo:chebi/smiles,otar:canonicalSmiles,otar:inchiKey,impc:pmId,impc:humanGeneAccId,monarch:iri,skos:exactMatch,ncit:P368,ncit:C98965,dcterms:identifier,oboinowl:hasAlternativeId,robokop:equivalent_identifiers,mesh.vocab:identifier", "--in-prefix-map-json", concat!(env!("CARGO_MANIFEST_DIR"), "/../../prefix_maps/prefix_map_normalise.json")]).stdin("merged.jsonl.000000").stdout("linked_nodes_test_clique_merge_000000.jsonl").output("linked_edges_test_clique_merge_000000.jsonl").output("linked_graph_metadata_test_clique_merge_000000.json")
        .run();
}
