apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Release.Name}}-summary-service-pvc
spec:
  storageClassName: standard-nfs-production
  volumeName: {{.Release.Name}}-summary-service-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi

