apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-resolver
  labels:
    app: {{ .Release.Name }}-resolver
spec:
  ports:
      - port: 8080
        targetPort: 8080
        name: http
        protocol: TCP
  selector:
    app: {{ .Release.Name }}-resolver