apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
  labels:
    app: {{ .Release.Name }}-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-backend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-backend
    spec:
      containers:
        - name: web
          image: ghcr.io/ebispot/grebi_api:{{.Values.imageTag}}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 8Gi
              cpu: 0.5
            limits:
              memory: 8Gi
              cpu: 0.5
          env:
            - name: GREBI_SOLR_HOST
              value: http://{{ .Release.Name }}-solr:8983
            - name: GREBI_NEO4J_HOST
              value: bolt://{{ .Release.Name }}-neo4j:7687
            - name: GREBI_CONTEXT_PATH
              value: /kg
            - name: JDK_JAVA_OPTIONS
              value: "-XX:InitialRAMPercentage=60.0 -XX:MinRAMPercentage=60.0 -XX:MaxRAMPercentage=80.0"
              
