id: Robokop.HumanGOA
enabled: true
description: "Curated GO term assignments to proteins in UniProtKB, RNA molecules from RNACentral, and protein complexes from the Complex Portal, from the GO Consortium's Human GOA resource"
download:
  - dest: robokop/hgoa_edges.jsonl.gz
    sources:
      - https://stars.renci.org/var/plater/bl-4.2.1/HumanGOA_Automat/06f107a4e9e8e547/edges.jsonl.gz
  - dest: robokop/hgoa_nodes.jsonl.gz
    sources:
      - https://stars.renci.org/var/plater/bl-4.2.1/HumanGOA_Automat/06f107a4e9e8e547/nodes.jsonl.gz
ingests:
  - globs: ["robokop/hgoa_edges.jsonl.gz"]
    command: '
      zcat $GREBI_INGEST_FILENAME |
      grebi_ingest_kgx_edges
          --kgx-inject-key-prefix robokop:'
  - globs: ["robokop/hgoa_nodes.jsonl.gz"]
    command: '
      zcat $GREBI_INGEST_FILENAME |
      grebi_transform_jsonl
          --json-rename category:grebi:type
          --json-inject-key-prefix robokop:'