id: Robokop.ICEES
enabled: true
description: "Clinical data (e.g., electronic health records, survey data) integrated at the patient level with environmental exposures data (e.g., airborne pollutants, socio-economic indicators) from ICEES"
download:
  - dest: robokop/icees_edges.jsonl.gz
    sources:
      - https://stars.renci.org/var/plater/bl-4.2.1/icees-kg/1.5.0/edges.jsonl.gz
  - dest: robokop/icees_nodes.jsonl.gz
    sources:
      - https://stars.renci.org/var/plater/bl-4.2.1/icees-kg/1.5.0/nodes.jsonl.gz
ingests:
  - globs: ["robokop/icees_edges.jsonl.gz"]
    command: '
      zcat $GREBI_INGEST_FILENAME |
      grebi_ingest_kgx_edges
          --kgx-inject-key-prefix robokop:'
  - globs: ["robokop/icees_nodes.jsonl.gz"]
    command: '
      zcat $GREBI_INGEST_FILENAME |
      grebi_transform_jsonl
          --json-rename category:grebi:type
          --json-inject-key-prefix robokop:'