id: OLS.upheno
enabled: true
download:
  - dest: ols_embeddings/text-embedding-3-small_pca512/upheno.parquet
    sources:
      - /nfs/production/parkinso/spot/ols4/dev2/out/embeddings/text-embedding-3-small_pca512/upheno.parquet
      - https://ftp.ebi.ac.uk/pub/databases/spot/ols/dev2/embeddings/text-embedding-3-small_pca512/upheno.parquet
ingests:
  - globs: ["ols_embeddings/text-embedding-3-small_pca512/upheno.parquet"]
    command: '
      cat $GREBI_INGEST_FILENAME |
      grebi_parquet2jsonl |
      grebi_transform_jsonl
        --json-select-by-value string_type:LABEL
        --json-select-keys iri,embedding
        --json-rename iri:id
        --json-rename embedding:embedding:text-embedding-3-small_pca512
          '
