download:
  - dest: ols_embeddings/text-embedding-3-small_pca512.json
    sources:
      - /nfs/production/parkinso/spot/ols4/dev2/out/embeddings/text-embedding-3-small_pca512.json
      - https://ftp.ebi.ac.uk/pub/databases/spot/ols/dev2/embeddings/text-embedding-3-small_pca512.json
ingests: []
