apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
  labels:
    app: {{ .Release.Name }}-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-backend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-backend
    spec:
      volumes:
        - name: {{ .Release.Name }}-import
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-import-pvc
      containers:
        - name: web
          image: ghcr.io/ebispot/grebi_api:{{.Values.imageTag}}
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: "/data_import"
              name: {{ .Release.Name }}-import
              readOnly: true
          ports:
            - containerPort: 8090
          resources:
            requests:
              memory: 8Gi
              cpu: 0.5
            limits:
              memory: 8Gi
              cpu: 0.5
          env:
            - name: GREBI_SOLR_HOST
              value: http://{{ .Release.Name }}-solr:8983
            - name: GREBI_NEO4J_HOSTS
              value: bolt://{{ .Release.Name }}-{{.Values.subgraph1 | replace "_" "-" }}-neo4j:7687;bolt://{{ .Release.Name }}-{{.Values.subgraph2 | replace "_" "-"}}-neo4j:7687
            - name: GREBI_RESOLVER_HOST
              value: http://{{ .Release.Name }}-resolver:8080
            - name: GREBI_METADATA_HOST
              value: http://{{ .Release.Name }}-metadata-service:8081
            - name: GREBI_PREFIX_HOST
              value: http://{{ .Release.Name }}-prefix-service:8082
            - name: GREBI_CONTEXT_PATH
              value: /kg
            - name: JDK_JAVA_OPTIONS
              value: "-XX:InitialRAMPercentage=60.0 -XX:MinRAMPercentage=60.0 -XX:MaxRAMPercentage=80.0"
            - name: GREBI_QUERY_TEMPLATES_PATH
              value: /data_import/query_templates
              
