apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
  labels:
    app: {{ .Release.Name }}-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-backend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-backend
    spec:
      {{- $postgresSecretName := include "grebi.postgresSecretName" . }}
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: {{ .Release.Name }}-import
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-import-pvc
      containers:
        - name: web
          image: ghcr.io/ebispot/grebi_api:{{.Values.imageTag}}
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - mountPath: "/data_import"
              name: {{ .Release.Name }}-import
              readOnly: true
          ports:
            - containerPort: 8090
          resources:
            requests:
              memory: 8Gi
              cpu: 0.5
            limits:
              memory: 8Gi
              cpu: 0.5
          envFrom:
            - secretRef:
                name: {{ $postgresSecretName }}
          env:
            - name: GREBI_CYPHER_HOST
              value: http://{{ .Release.Name }}-cypher-service:8085
            - name: GREBI_CONTEXT_PATH
              value: /kg
            - name: JDK_JAVA_OPTIONS
              value: "-XX:InitialRAMPercentage=60.0 -XX:MinRAMPercentage=60.0 -XX:MaxRAMPercentage=80.0"
            - name: GREBI_QUERY_TEMPLATES_PATH
              value: /data_import/query_templates
            - name: GREBI_EMBEDDING_SERVICE_URL
              value: http://spot-embedding-service:5000
              
