###
### Read-write local disk to run the databases
### These each belong to a specific worker node
###
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: worker-1-local-pvc
spec:
  storageClassName: local-storage
  volumeName: worker-1-local-pv
  accessModes: ['ReadWriteMany']
  resources:
    requests:
      storage: {{.Values.local_disk}}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
  finalizers:
  - kubernetes.io/pv-protection
  name: worker-1-local-pv
spec:
  accessModes: ['ReadWriteMany']
  capacity:
    storage: {{.Values.local_disk}}
  local:
    path: /var/local-disk
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - hh-rke-wp-webadmin-58-worker-1.caas.ebi.ac.uk
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: worker-2-local-pvc
spec:
  storageClassName: local-storage
  volumeName: worker-2-local-pv
  accessModes: ['ReadWriteMany']
  resources:
    requests:
      storage: {{.Values.local_disk}}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
  finalizers:
  - kubernetes.io/pv-protection
  name: worker-2-local-pv
spec:
  accessModes: ['ReadWriteMany']
  capacity:
    storage: {{.Values.local_disk}}
  local:
    path: /var/local-disk
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - hh-rke-wp-webadmin-58-worker-2.caas.ebi.ac.uk
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: worker-3-local-pvc
spec:
  storageClassName: local-storage
  volumeName: worker-3-local-pv
  accessModes: ['ReadWriteMany']
  resources:
    requests:
      storage: {{.Values.local_disk}}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
  finalizers:
  - kubernetes.io/pv-protection
  name: worker-3-local-pv
spec:
  accessModes: ['ReadWriteMany']
  capacity:
    storage: {{.Values.local_disk}}
  local:
    path: /var/local-disk
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - hh-rke-wp-webadmin-58-worker-3.caas.ebi.ac.uk
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: worker-4-local-pvc
spec:
  storageClassName: local-storage
  volumeName: worker-4-local-pv
  accessModes: ['ReadWriteMany']
  resources:
    requests:
      storage: {{.Values.local_disk}}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
  finalizers:
  - kubernetes.io/pv-protection
  name: worker-4-local-pv
spec:
  accessModes: ['ReadWriteMany']
  capacity:
    storage: {{.Values.local_disk}}
  local:
    path: /var/local-disk
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - hh-rke-wp-webadmin-58-worker-4.caas.ebi.ac.uk
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem