apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-metadata-service
  labels:
    app: {{ .Release.Name }}-metadata-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-metadata-service
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-metadata-service
    spec:
      volumes:
        - name: {{ .Release.Name }}-import
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-import-pvc
      containers:
        - name: metadata-service
          image: ghcr.io/ebispot/grebi_metadata_service:{{.Values.imageTag}}
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: "/data_import"
              name: {{ .Release.Name }}-import
              readOnly: true
          resources:
            requests:
              memory: 3Gi
              cpu: 0.5
            limits:
              memory: 3Gi
              cpu: 0.5
          env:
            - name: GREBI_METADATA_JSON_SEARCH_PATH
              value: /data_import/metadata
            - name: JAVA_TOOL_OPTIONS
              value: -Xmx2048m
          ports:
            - containerPort: 8081

