apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-postgres
  labels:
    app: {{ .Release.Name }}-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-postgres
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-postgres
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                    - hh-rke-wp-webadmin-58-worker-{{.Values.postgres_worker_n}}.caas.ebi.ac.uk
      volumes:
        - name: {{ .Release.Name }}-import
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-import-pvc
      securityContext:
        runAsUser: 5533
        runAsGroup: 1279
        fsGroup: 1279
      containers:
        - name: postgres
          image: pgvector/pgvector:0.8.2-pg18
          volumeMounts:
            - mountPath: "/data_import"
              name: {{ .Release.Name }}-import
          command: ["/bin/bash", "-c"]
          args: ["chmod 700 /data_import/postgres/postgres_data && exec postgres -D /data_import/postgres/postgres_data -p 5432 -c shared_buffers=4GB -c work_mem=256MB -c maintenance_work_mem=512MB -c effective_cache_size=12GB -c jit=off -c plan_cache_mode=force_generic_plan -c random_page_cost=4"]
          resources:
            requests:
              memory: 16Gi
              cpu: 4
            limits:
              memory: 16Gi
              cpu: 4
          env:
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
          ports:
            - containerPort: 5432
