apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
  labels:
    app: {{ .Release.Name }}-backend
spec:
  type: NodePort
  ports:
  - name: "application"
    port: 8090
  selector:
    app: {{ .Release.Name }}-backend
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend
  labels:
    app: {{ .Release.Name }}-frontend
spec:
  type: NodePort
  ports:
  - name: "application"
    port: 8080
  selector:
    app: {{ .Release.Name }}-frontend
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{.Values.subgraph1 | replace "_" "-" }}-neo4j
  labels:
    app: {{ .Release.Name }}-{{.Values.subgraph1 | replace "_" "-" }}-neo4j
spec:
  ports:
      - port: 7474
        targetPort: 7474
        name: http
        protocol: TCP
      - port: 7687
        targetPort: 7687
        name: bolt
        protocol: TCP
  selector:
    app: {{ .Release.Name }}-{{.Values.subgraph1 | replace "_" "-" }}-neo4j
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{.Values.subgraph2 | replace "_" "-" }}-neo4j
  labels:
    app: {{ .Release.Name }}-{{.Values.subgraph2 | replace "_" "-" }}-neo4j
spec:
  ports:
      - port: 7474
        targetPort: 7474
        name: http
        protocol: TCP
      - port: 7687
        targetPort: 7687
        name: bolt
        protocol: TCP
  selector:
    app: {{ .Release.Name }}-{{.Values.subgraph2 | replace "_" "-" }}-neo4j
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-resolver
  labels:
    app: {{ .Release.Name }}-resolver
spec:
  ports:
      - port: 8080
        targetPort: 8080
        name: http
        protocol: TCP
  selector:
    app: {{ .Release.Name }}-resolver
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-solr
  labels:
    app: {{ .Release.Name }}-solr
spec:
  ports:
      - port: 8983
        targetPort: 8983
        name: http
        protocol: TCP
  selector:
    app: {{ .Release.Name }}-solr
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-metadata-service
  labels:
    app: {{ .Release.Name }}-metadata-service
spec:
  ports:
      - port: 8081
        targetPort: 8081
        name: http
        protocol: TCP
  selector:
    app: {{ .Release.Name }}-metadata-service
