apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
  labels:
    app: {{ .Release.Name }}-backend
spec:
  type: NodePort
  ports:
  - name: "application"
    port: 8090
  selector:
    app: {{ .Release.Name }}-backend
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend
  labels:
    app: {{ .Release.Name }}-frontend
spec:
  type: NodePort
  ports:
  - name: "application"
    port: 8080
  selector:
    app: {{ .Release.Name }}-frontend
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-cypher-service
  labels:
    app: {{ .Release.Name }}-cypher-service
spec:
  ports:
      - port: 8085
        targetPort: 8085
        name: http
        protocol: TCP
  selector:
    app: {{ .Release.Name }}-cypher-service
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-prefix-service
  labels:
    app: {{ .Release.Name }}-prefix-service
spec:
  ports:
      - port: 8082
        targetPort: 8082
        name: http
        protocol: TCP
  selector:
    app: {{ .Release.Name }}-prefix-service
