apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-solr
  labels:
    app: {{ .Release.Name }}-solr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-solr
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-solr
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                    - hh-rke-wp-webadmin-58-worker-{{.Values.solr_worker_n}}.caas.ebi.ac.uk
      securityContext:
        runAsUser: 8983
        runAsGroup: 8983
        fsGroup: 8983
      volumes:
        - name: {{ .Release.Name }}-import
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-import-pvc
        - name: {{ .Release.Name }}-solr
          persistentVolumeClaim:
            claimName: worker-{{.Values.solr_worker_n}}-local-pvc
      containers:
        - name: solr
          image: ghcr.io/ebispot/grebi_solr_with_extras:9.5.0
          volumeMounts:
            - mountPath: "/data_import"
              name: {{ .Release.Name }}-import
              readOnly: true
            - mountPath: "/data"
              name: {{ .Release.Name }}-solr
          command: ["/bin/bash", "-c"]
          args: ["echo Synchronizing data... && rsync --mkpath -arv --no-t --omit-dir-times --delete /data_import/solr/ $SOLR_HOME/ && echo Done && solr-foreground -a -XX:CompileCommand=exclude,com.github.benmanes.caffeine.cache.BoundedLocalCache::put"]
          resources:
            requests:
              memory: 4Gi
              cpu: 1
            limits:
              memory: 4Gi
              cpu: 1
          env:
            - name: SOLR_HOME
              value: /data/solr
          ports:
            - containerPort: 8983

