id: HETT_Pesticides.APPRIL
enabled: true
description: "Australian Pesticides and Veterinary Medicines Authority approved pesticides data"
download:
  - dest: hett_pesticides/apprildatadump_public.xlsx
    sources:
      - https://ftp.ebi.ac.uk/pub/databases/spot/kg/data/apprildatadump_public.xlsx
ingests:
  - globs: ["hett_pesticides/apprildatadump_public.xlsx"]
    command: '
      cat $GREBI_INGEST_FILENAME |
      $GREBI_DATALOAD_HOME/01_ingest/hett_pesticides_appril.py --datasource-name $GREBI_INGEST_DATASOURCE_NAME'
