import raw from "./db_links.json";

/** Where an identifier or datasource lives on the web. */
export interface ExternalLink {
  url: string;
  /** the database the link goes to, for tooltips */
  database: string;
  /** an icon file under db_icons/, when the database has one */
  icon?: string;
  /** hosted by EMBL-EBI */
  ebi: boolean;
}

interface Database { name: string; homepage: string; icon?: string; ebi?: boolean }
interface Prefix { name: string; url: string; pattern?: string; db?: string }
interface Rule { regex: string; db: string; url: string }
interface Datasource { db: string; homepage?: string }
interface DbLinks {
  databases: Record<string, Database>;
  prefixes: Record<string, Prefix>;
  rules: Rule[];
  datasources: Record<string, Datasource>;
}

// generated by scripts/make_db_links.py: Bioregistry plus the curated EBI routes
const data = raw as unknown as DbLinks;
const rules = data.rules.map((r) => ({ ...r, regex: new RegExp(r.regex) }));
const idPatterns = new Map<string, RegExp | null>();

/** The URL of an icon file, under the site's public URL. */
export function dbIconUrl(icon: string): string {
  return (process.env.PUBLIC_URL || "/").replace(/\/+$/, "") + "/db_icons/" + icon;
}

function fill(template: string, placeholder: string, value: string): string {
  return template.split(placeholder).join(value);
}

// the characters that would change the structure of the URL an id is dropped into
function escapeId(id: string): string {
  return id.replace(/[#?&"<>`]/g, (c) => encodeURIComponent(c));
}

function link(url: string, dbKey: string | undefined, fallbackName: string): ExternalLink {
  const db = dbKey ? data.databases[dbKey] : undefined;
  return { url, database: db?.name || fallbackName, icon: db?.icon, ebi: !!db?.ebi };
}

function idPattern(prefix: string, entry: Prefix): RegExp | null {
  if (!idPatterns.has(prefix)) {
    let re: RegExp | null = null;
    if (entry.pattern) {
      try {
        re = new RegExp(entry.pattern);
      } catch {
        re = null;
      }
    }
    idPatterns.set(prefix, re);
  }
  return idPatterns.get(prefix) || null;
}

function linkForCurie(prefix: string, local: string): ExternalLink | null {
  const entry = data.prefixes[prefix];
  if (!entry) return null;
  const pattern = idPattern(prefix, entry);
  if (pattern && !pattern.test(local)) return null;
  return link(fill(entry.url, "$1", escapeId(local)), entry.db, entry.name);
}

/**
 * Where an identifier lives on the web, or null when it is not a known kind of id.
 *
 * Prefixed ids (mondo:0005083) go through the Bioregistry prefix table, with
 * EBI-hosted ids routed to their EBI home (OLS for ontology terms) and the
 * local part checked against the prefix's id pattern where Bioregistry has
 * one. Ids without a prefix (GCST000187, ENSG00000146648) go through the
 * regex rules. An IRI links to itself.
 */
export function externalLinkForId(id: string): ExternalLink | null {
  if (typeof id !== "string") return null;
  const s = id.trim();
  if (!s || s.length > 500 || /\s/.test(s)) return null;
  for (const rule of rules) {
    if (rule.regex.test(s)) return link(fill(rule.url, "$0", escapeId(s)), rule.db, s);
  }
  if (/^https?:\/\//i.test(s)) {
    let host: string;
    try {
      host = new URL(s).hostname;
    } catch {
      return null;
    }
    return { url: s, database: host, ebi: host.endsWith("ebi.ac.uk") };
  }
  const colon = s.indexOf(":");
  if (colon <= 0 || colon === s.length - 1) return null;
  const prefix = s.slice(0, colon).toLowerCase();
  const local = s.slice(colon + 1);
  if (prefix === "obo") {
    // obo:UBERON_0002048 is UBERON's own prefix in OBO PURL spelling
    const m = /^([A-Za-z][A-Za-z0-9]*)_(.+)$/.exec(local);
    if (m) {
      const own = linkForCurie(m[1].toLowerCase(), m[2]);
      if (own) return own;
    }
  }
  return linkForCurie(prefix, local);
}

/** The homepage of a GrEBI datasource (GWAS, OLS.mondo, Robokop.Pharos), or null when unknown. */
export function externalLinkForDatasource(ds: string): ExternalLink | null {
  if (typeof ds !== "string" || !ds) return null;
  let entry: Datasource | undefined = data.datasources[ds];
  let member: string | undefined;
  if (!entry) {
    const dot = ds.indexOf(".");
    if (dot > 0) {
      // a family such as OLS.<ontology>
      entry = data.datasources[ds.slice(0, dot + 1)];
      member = ds.slice(dot + 1);
    }
  }
  if (!entry) return null;
  const db = data.databases[entry.db];
  const template = entry.homepage || db?.homepage;
  if (!template) return null;
  const url = fill(template, "$1", member ? encodeURIComponent(member) : "");
  return { url, database: db?.name || ds, icon: db?.icon, ebi: !!db?.ebi };
}

/** Source ids in display order: EBI-hosted links first, other links next, ids with no link last. */
export function orderSourceIds(ids: string[]): string[] {
  const rank = (id: string) => {
    const l = externalLinkForId(id);
    return l ? (l.ebi ? 0 : 1) : 2;
  };
  return ids
    .map((id, i) => ({ id, i, r: rank(id) }))
    .sort((a, b) => a.r - b.r || a.i - b.i)
    .map((x) => x.id);
}
