name: OLS.go
enabled: true
ingests:
  - globs: ["/data/ontologies/ontologies.json"]
    command: '
      grebi_ingest_ols
        --datasource-name $GREBI_INGEST_DATASOURCE_NAME
        --ontologies go
        --skip-obsolete
      '