name: OpenTargets
enabled: true
ingests:
  - globs: ["dataload/00_fetch_data/otar/evidence/*/*.parquet"]
    command: '
      grebi_parquet2jsonl |
      grebi_transform_jsonl
          --json-inject-type otar:Evidence
          --json-inject-key-prefix otar:
          --json-inject-value-prefix literature:pmid:
          --json-inject-value-prefix targetId:ensembl:
          --json-de-nest-field diseaseModelAssociatedHumanPhenotypes.id
          --json-de-nest-field diseaseModelAssociatedModelPhenotypes.id
          '
