name: OpenTargets
enabled: true
ingests:
  - globs: ["dataload/00_fetch_data/otar/drug_molecule/*.parquet"]
    command: '
      grebi_parquet2jsonl |
      grebi_transform_jsonl
        --json-inject-type biolink:Drug
        --json-inject-value-prefix id:chembl:
        --json-de-nest-field crossReferences.ids
        --json-rename linkedDiseases.rows:linkedDiseases
        --json-rename linkedTargets.rows:linkedTargets |
      grebi_transform_jsonl
        --json-inject-key-prefix otar:'
