name: OpenTargets
enabled: true
download:
  - dest: otar/evidence/
    sources:
      - /nfs/production/parkinso/spot/jmcl/otar/output/evidence/*/*.parquet
ingests:
  - globs: ["otar/evidence/*/*.parquet"]
    command: '
      cat $GREBI_INGEST_FILENAME |
      grebi_parquet2jsonl |
      grebi_transform_jsonl
          --json-inject-type otar:Evidence
          --json-inject-key-prefix otar:
          --json-inject-value-prefix literature:pmid:
          --json-inject-value-prefix targetId:ensembl:
          --json-de-nest-field diseaseModelAssociatedHumanPhenotypes.id
          --json-de-nest-field diseaseModelAssociatedModelPhenotypes.id
          '
