name: OpenTargets
enabled: true
download:
  - dest: otar/drug_molecule/
    sources:
      - /nfs/ftp/public/databases/opentargets/platform/25.09/output/drug_molecule/*.parquet
ingests:
  - globs: ["otar/drug_molecule/*.parquet"]
    command: '
      cat $GREBI_INGEST_FILENAME |
      grebi_parquet2jsonl |
      grebi_transform_jsonl
        --json-inject-type biolink:Drug
        --json-inject-value-prefix id:chembl:
        --json-de-nest-field crossReferences.ids
        --json-rename linkedDiseases.rows:linkedDiseases
        --json-rename linkedTargets.rows:linkedTargets |
      grebi_transform_jsonl
        --json-inject-key-prefix otar:'
