id: OpenTargets
enabled: true
description: "Drug molecule data including compound information from the Open Targets evidence pipeline"
download:
  - dest: otar/drug_molecule/
    sources:
      - /nfs/production/parkinso/spot/jmcl/otar/output/drug_molecule/part-00000-871f412e-aec4-4d33-a50d-feee532ddcd2-c000.snappy.parquet
ingests:
  - globs: ["otar/drug_molecule/*.parquet"]
    command: '
      cat $GREBI_INGEST_FILENAME |
      grebi_parquet2jsonl |
      grebi_transform_jsonl
        --json-inject-type biolink:Drug
        --json-inject-value-prefix id:chembl:
        --json-de-nest-field crossReferences.ids
        --json-rename linkedDiseases.rows:linkedDiseases
        --json-rename linkedTargets.rows:linkedTargets |
      grebi_transform_jsonl
        --json-inject-key-prefix otar:'
