name: OpenTargets
enabled: true
download:
  - dest: otar/drug_indication/
    sources:
      - /nfs/production/parkinso/spot/jmcl/otar/output/drug_indication/part-00000-d933a69d-d5ec-42b6-9c76-38bc8ca8d735-c000.snappy.parquet
ingests:
  - globs: ["otar/drug_indication/*.parquet"]
    command: '
      cat $GREBI_INGEST_FILENAME |
      grebi_parquet2jsonl |
      grebi_transform_jsonl --json-select-keys id,indications |
      grebi_unwind --unwind-field indications |
      grebi_transform_jsonl
        --json-inject-type biolink:Drug
        --json-inject-value-prefix id:chembl:
        --json-de-nest-field indications.disease
        --json-rename indications:biolink:treats
          '
  - globs: ["otar/drug_indication/*.parquet"]
    command: '
      cat $GREBI_INGEST_FILENAME |
      grebi_parquet2jsonl |
      grebi_transform_jsonl
        --json-inject-type biolink:Drug
        --json-inject-value-prefix id:chembl:
        --json-select-keys id,approvedIndications
        --json-inject-key-prefix otar:
          '

