id: OpenTargets
enabled: true
description: "Disease-to-phenotype associations derived from the Open Targets evidence pipeline"
download:
  - dest: otar/disease_phenotype/
    sources:
      - /nfs/production/parkinso/spot/jmcl/otar/output/disease_phenotype/disease_phenotype.parquet
ingests:
  - globs: ["otar/disease_phenotype/*.parquet"]
    command: '
      cat $GREBI_INGEST_FILENAME |
      grebi_parquet2jsonl |
      grebi_nodes2edges --from-field disease --to-field phenotype --edge-type biolink:has_phenotype |
      grebi_transform_jsonl
        --json-inject-type biolink:Disease
        --json-inject-key-prefix otar:
          '