name: Biomappings
enabled: true
download:
  - dest: biomappings/mappings.tsv
    sources:
      - https://raw.githubusercontent.com/biopragmatics/biomappings/refs/heads/master/src/biomappings/resources/mappings.tsv
ingests:
  - globs: ["biomappings/mappings.tsv"]
    command: '
      python3 $GREBI_DATALOAD_HOME/01_ingest/biomappings_transform.py |
      grebi_transform_jsonl --json-inject-key-prefix biomappings:'
