name: text-embedding-3-small
enabled: true
download:
  - dest: ols_embeddings/text-embedding-3-small_pca512_avg.parquet
    sources:
      - https://ftp.ebi.ac.uk/pub/databases/spot/ols_embeddings/latest/text-embedding-3-small_pca512_avg.parquet
ingests:
  - globs: ["ols_embeddings/text-embedding-3-small_pca512_avg.parquet"]
    command: '
      cat $GREBI_INGEST_FILENAME |
      grebi_parquet2jsonl |
      grebi_transform_jsonl
        --json-select-keys iri,embedding
        --json-rename iri:id
        --json-rename embedding:embedding:text-embedding-3-small_pca512
          '