name: GWAS
enabled: true
ingests: 
  - globs:
      - "./gwas-catalog-associations_ontology-annotated.tsv"
      - "./gwas-catalog-studies-download-alternative-v1.0.2.1.txt"
    command: '
      grebi_ingest_gwas
          --datasource-name $GREBI_INGEST_DATASOURCE_NAME
          --filename $GREBI_INGEST_FILENAME
    '
    