name: GWAS
enabled: true
download:
  - dest: gwas/gwas-catalog-associations_ontology-annotated.tsv
    sources:
      - https://www.ebi.ac.uk/gwas/api/search/downloads/full
  - dest: gwas/gwas-catalog-studies-download-alternative-v1.0.2.1.txt
    sources:
      - https://www.ebi.ac.uk/gwas/api/search/downloads/studies_alternative
ingests:
  - globs:
      - "gwas/gwas-catalog-associations_ontology-annotated.tsv"
      - "gwas/gwas-catalog-studies-download-alternative-v1.0.2.1.txt"
    command: '
      cat $GREBI_INGEST_FILENAME |
      grebi_ingest_gwas
          --filename $GREBI_INGEST_FILENAME'
    