name: GWAS
enabled: true
download:
  - dest: gwas/
    sources:
      - https://ftp.ebi.ac.uk/pub/databases/gwas/releases/latest/gwas-catalog-associations_ontology-annotated-full.zip
  - dest: gwas/gwas-catalog-studies-download-alternative-v1.0.2.1.txt
    sources:
      - https://ftp.ebi.ac.uk/pub/databases/gwas/releases/latest/gwas-catalog-studies-download-alternative-v1.0.2.1.txt
ingests:
  - globs:
      - "gwas/gwas-catalog-download-associations-alt-full.tsv"
      - "gwas/gwas-catalog-studies-download-alternative-v1.0.2.1.txt"
    command: '
      cat $GREBI_INGEST_FILENAME |
      grebi_ingest_gwas
          --filename $GREBI_INGEST_FILENAME'
    