name: HelloWorld
enabled: true
ingests:
  - globs: ["dataload/00_fetch_data/hello_world/valid_edges.jsonl"]
    command: '
      grebi_ingest_kgx_edges
          --kgx-inject-key-prefix helloworld:'
  - globs: ["dataload/00_fetch_data/hello_world/valid_nodes.jsonl"]
    command: '
      grebi_transform_jsonl
          --json-rename category:grebi:type
          --json-inject-key-prefix helloworld:'

