name: HETT_Pesticides.EU
enabled: true
ingests:
  - globs: ["./00_fetch_data/hett_pesticides/ActiveSubstanceExport*"]
    command: $GREBI_HOME/01_ingest/hett_pesticides_eu.py --datasource-name $GREBI_INGEST_DATASOURCE_NAME
