name: HETT_Pesticides.EU
enabled: true
download:
  - dest: hett_pesticides/ActiveSubstanceExport.xlsx
    sources:
      - hett_pesticides/ActiveSubstanceExport.xlsx
ingests:
  - globs: ["hett_pesticides/ActiveSubstanceExport*"]
    command: '
      cat $GREBI_INGEST_FILENAME |
      $GREBI_DATALOAD_HOME/01_ingest/hett_pesticides_eu.py --datasource-name $GREBI_INGEST_DATASOURCE_NAME'
