id: HRA
enabled: true
description: "Anatomical structure data from the NIH Human BioMolecular Atlas Program (HuBMAP)"
download:
  - dest: hra_kg/graph.nt
    sources:
      - https://cdn.humanatlas.io/digital-objects/collection/hra/v2.2/graph.nt
ingests:
  - globs: ["hra_kg/graph.nt"]
    command: '
      cat $GREBI_INGEST_FILENAME |
      grebi_rdf2jsonl --rdf-type rdf_triples_turtle --rdf-types-are-grebi-types'
