name: HRA
enabled: true
ingests:
  - globs: ["/nfs/production/parkinso/spot/hra/dataload/tmp/out/ontologies.json"]
    command: '
      grebi_ingest_ols --datasource-name $GREBI_INGEST_DATASOURCE_NAME
          --ontologies ccf,hra
    ' 
