name: IMPC
enabled: true
ingests:
  - globs: ["/nfs/production/parkinso/spot/jmcl/impc-kg/categorical_observation_json/*.json.gz"]
    command: '
      grebi_transform_jsonl
          --json-rename-field observationId:id
          --json-inject-type impc:CategoricalObservation
          --json-inject-key-prefix impc:'
  - globs: ["/nfs/production/parkinso/spot/jmcl/impc-kg/time_series_observation_json/*.json.gz"]
    command: '
        grebi_transform_jsonl
            --json-rename-field observationId:id
            --json-inject-type impc:TimeSeriesObservation
            --json-inject-key-prefix impc:'
  - globs: ["/nfs/production/parkinso/spot/jmcl/impc-kg/unidimensional_observation_json/*.json.gz"]
    command: '
        grebi_transform_jsonl
            --json-rename-field observationId:id
            --json-inject-type impc:UnidimensionalObservation
            --json-inject-key-prefix impc:'
  - globs: ["/nfs/production/parkinso/spot/jmcl/impc-kg/statistical_result_json/*.json.gz"]
    command: '
        grebi_transform_jsonl
            --json-rename-field statisticalResultId:id
            --json-inject-type impc:StatisticalResult
            --json-inject-key-prefix impc:
            --json-de-nest-field potentialPhenotypes.id
            --json-de-nest-field statisticalMethod.name'
  - globs: ["/nfs/production/parkinso/spot/jmcl/impc-kg/specimen_experiment_json/*.json.gz"]
    command: '
        grebi_transform_jsonl
            --json-rename-field experimentId:id
            --json-inject-type impc:SpecimenExperiment
            --json-inject-key-prefix impc:'