id: MeSH
enabled: true
description: "The NLM controlled vocabulary thesaurus used for indexing articles in PubMed"
download:
  - dest: mesh/mesh2024.nt.gz
    sources:
      - https://nlmpubs.nlm.nih.gov/projects/mesh/rdf/2024/mesh2024.nt.gz
  - dest: mesh/vocabulary_1.0.0.ttl
    sources:
      - https://nlmpubs.nlm.nih.gov/projects/mesh/rdf/2024/vocabulary_1.0.0.ttl
ingests:
  - globs: ["mesh/mesh2024.nt.gz"]
    memory: "8 GB"
    command: '
      zcat $GREBI_INGEST_FILENAME |
      grebi_rdf2jsonl
          --rdf-type rdf_triples_turtle
          --rdf-types-are-grebi-types'
  - globs: ["mesh/vocabulary_1.0.0.ttl"]
    command: '
      cat $GREBI_INGEST_FILENAME |
      grebi_rdf2jsonl
          --rdf-type rdf_triples_turtle
          --rdf-types-are-grebi-types'
