id: MGnify
enabled: true
description: "EMBL-EBI's resource for the analysis and archival of metagenomic and metatranscriptomic sequence data"
download:
  - dest: mgnify/mgnify_nodes.jsonl.gz
    sources:
      - https://ftp.ebi.ac.uk/pub/databases/spot/kg/data/mgnify_nodes.jsonl.gz
  - dest: mgnify/mgnify_edges.jsonl.gz
    sources:
      - https://ftp.ebi.ac.uk/pub/databases/spot/kg/data/mgnify_edges.jsonl.gz
ingests:
  - globs: ["mgnify/*.jsonl.gz"]
    command: zcat $GREBI_INGEST_FILENAME
