name: OLS.chebi
enabled: true
download:
  - dest: ols/chebi.json.gz
    sources:
      - https://ftp.ebi.ac.uk/pub/databases/spot/ols/dev/latest/ontology_jsons/chebi.json.gz
ingests:
  - globs: ["ols/chebi.json.gz"]
    command: '
      zcat $GREBI_INGEST_FILENAME |
      grebi_ingest_ols
        --ontologies chebi
        --skip-obsolete'