name: OLS.ncit
enabled: true
download:
  - dest: ols/ncit.json.gz
    sources:
      - https://ftp.ebi.ac.uk/pub/databases/spot/ols/dev/latest/ontology_jsons/ncit.json.gz
ingests:
  - globs: ["ols/ncit.json.gz"]
    command: '
      zcat $GREBI_INGEST_FILENAME |
      grebi_ingest_ols
        --ontologies ncit
        --skip-obsolete'