name: OLS.biolink
enabled: true
download:
  - dest: ols/biolink.json.gz
    sources:
      - https://ftp.ebi.ac.uk/pub/databases/spot/ols/dev/latest/ontology_jsons/biolink.json.gz
ingests:
  - globs: ["ols/biolink.json.gz"]
    command: '
      zcat $GREBI_INGEST_FILENAME |
      grebi_ingest_ols
        --ontologies biolink
        --skip-obsolete'