name: OLS.ncbitaxon
enabled: true
download:
  - dest: ols/ncbitaxon.json.gz
    sources:
      - https://ftp.ebi.ac.uk/pub/databases/spot/ols/dev/latest/ontology_jsons/ncbitaxon.json.gz
ingests:
  - globs: ["ols/ncbitaxon.json.gz"]
    command: '
      zcat $GREBI_INGEST_FILENAME |
      grebi_ingest_ols
        --ontologies ncbitaxon
        --skip-obsolete'