name: OLS.mp
enabled: true
download:
  - dest: ols/mp.json.gz
    sources:
      - https://ftp.ebi.ac.uk/pub/databases/spot/ols/dev/latest/ontology_jsons/mp.json.gz
ingests:
  - globs: ["ols/mp.json.gz"]
    command: '
      zcat $GREBI_INGEST_FILENAME |
      grebi_ingest_ols
        --ontologies mp
        --skip-obsolete'