name: OLS.ecto
enabled: true
download:
  - dest: ols/ecto.json.gz
    sources:
      - https://ftp.ebi.ac.uk/pub/databases/spot/ols/dev/latest/ontology_jsons/ecto.json.gz
ingests:
  - globs: ["ols/ecto.json.gz"]
    command: '
      zcat $GREBI_INGEST_FILENAME |
      grebi_ingest_ols
        --ontologies ecto
        --skip-obsolete'