id: ols_top_k
enabled: true
description: "Precomputed top-k semantic similarity matches between OLS ontology terms"
download:
  - dest: ols_top_k/ols_top_k.tsv.gz
    sources:
      - https://ftp.ebi.ac.uk/pub/databases/spot/kg/ontology_top_k.tsv.gz
ingests:
  - globs: ["ols_top_k/ols_top_k.tsv.gz"]
    command: '
      zcat $GREBI_INGEST_FILENAME |
      grebi_tsv2jsonl
      | grebi_transform_jsonl
          --json-inject-key-prefix ols_top_k:
      | grebi_nodes2edges
          --from-field ols_top_k:iri_1
          --to-field ols_top_k:iri_2
          --edge-type ols_top_k:matches'
