name: OLS.eco
enabled: true
download:
  - dest: ols/eco.json.gz
    sources:
      - https://ftp.ebi.ac.uk/pub/databases/spot/ols/dev/latest/ontology_jsons/eco.json.gz
ingests:
  - globs: ["ols/eco.json.gz"]
    command: '
      zcat $GREBI_INGEST_FILENAME |
      grebi_ingest_ols
        --ontologies eco
        --skip-obsolete'