name: OLS.bfo
enabled: true
download:
  - dest: ols/bfo.json.gz
    sources:
      - https://ftp.ebi.ac.uk/pub/databases/spot/ols/dev/latest/ontology_jsons/bfo.json.gz
ingests:
  - globs: ["ols/bfo.json.gz"]
    command: '
      zcat $GREBI_INGEST_FILENAME |
      grebi_ingest_ols
        --ontologies bfo
        --skip-obsolete'