name: OLS.efo
enabled: true
download:
  - dest: ols/efo.json.gz
    sources:
      - https://ftp.ebi.ac.uk/pub/databases/spot/ols/dev/latest/ontology_jsons/efo.json.gz
ingests:
  - globs: ["ols/efo.json.gz"]
    command: '
      zcat $GREBI_INGEST_FILENAME |
      grebi_ingest_ols
        --ontologies efo
        --skip-obsolete'