name: OLS.so
enabled: true
download:
  - dest: ols/so.json.gz
    sources:
      - https://ftp.ebi.ac.uk/pub/databases/spot/ols/dev/latest/ontology_jsons/so.json.gz
ingests:
  - globs: ["ols/so.json.gz"]
    command: '
      zcat $GREBI_INGEST_FILENAME |
      grebi_ingest_ols
        --ontologies so
        --skip-obsolete'