name: OLS
enabled: true
ingests:
  - globs: ["/nfs/production/parkinso/spot/ols4/prod/slurm_pipeline/ontologies.json.gz"]
    command: '
      grebi_ingest_ols
        --datasource-name $GREBI_INGEST_DATASOURCE_NAME
        --ontologies efo,mp,hp,ro,iao,uberon,pato,oba,bspo,iao,obi,bfo,cob,oio,iao,biolink,mondo,doid,dc,dcterms,ncit,edam,upheno
        --skip-obsolete'
