name: OLS.dc
enabled: true
download:
  - dest: ols/dc.json.gz
    sources:
      - https://ftp.ebi.ac.uk/pub/databases/spot/ols/dev/latest/ontology_jsons/dc.json.gz
ingests:
  - globs: ["ols/dc.json.gz"]
    command: '
      zcat $GREBI_INGEST_FILENAME |
      grebi_ingest_ols
        --ontologies dc
        --skip-obsolete'