id: PrimeKG
enabled: true
description: "A precision medicine knowledge graph integrating 20 biomedical resources covering diseases, drugs, genes, and biological processes"
download:
  - dest: primekg/kg.csv
    sources:
      - https://dataverse.harvard.edu/api/access/datafile/6180620
ingests:
  - globs: ["primekg/kg.csv"]
    memory: "8 GB"
    command: '
      cat $GREBI_INGEST_FILENAME |
      $GREBI_DATALOAD_HOME/01_ingest/primekg.py'

