name: PrimeKG
enabled: true
download:
  - dest: primekg/kg.csv
    sources:
      - https://dataverse.harvard.edu/api/access/datafile/6180620
ingests:
  - globs: ["primekg/kg.csv"]
    command: '
      cat $GREBI_INGEST_FILENAME |
      $GREBI_DATALOAD_HOME/01_ingest/primekg.py'

