name: Reactome
enabled: true
download:
  - dest: reactome/reactome.json
    sources:
      - dataload/reactome/export/reactome.json
ingests:
    - globs: ["reactome/reactome.json"]
      command: '
        cat $GREBI_INGEST_FILENAME |
        grebi_ingest_reactome'
