name: Reactome
enabled: true
download:
  - dest: reactome/reactome.json.gz
    sources:
      - https://ftp.ebi.ac.uk/pub/databases/spot/kg/data/reactome.json.gz
ingests:
    - globs: ["reactome/reactome.json.gz"]
      command: '
        zcat $GREBI_INGEST_FILENAME |
        grebi_ingest_reactome'
