name: Robokop.DrugCentral
enabled: true
ingests:
  - globs: ["./00_fetch_data/robokop/drugcentral_edges.jsonl.gz"]
    command: '
      grebi_ingest_kgx_edges
          --kgx-inject-key-prefix robokop:'
  - globs: ["./00_fetch_data/robokop/drugcentral_nodes.jsonl.gz"]
    command: '
      grebi_transform_jsonl
          --json-rename-field category:grebi:type
          --json-inject-key-prefix robokop:'