name: SSSOM
enabled: true
download:
  - dest: sssom/gene_mappings.sssom.tsv
    sources:
      - https://data.monarchinitiative.org/mappings/latest/gene_mappings.sssom.tsv
  - dest: sssom/hp_mesh.sssom.tsv
    sources:
      - https://data.monarchinitiative.org/mappings/latest/hp_mesh.sssom.tsv
  - dest: sssom/mesh_chebi_biomappings.sssom.tsv
    sources:
      - https://data.monarchinitiative.org/mappings/latest/mesh_chebi_biomappings.sssom.tsv
  - dest: sssom/mondo.sssom.tsv
    sources:
      - https://data.monarchinitiative.org/mappings/latest/mondo.sssom.tsv
  - dest: sssom/umls_hp.sssom.tsv
    sources:
      - https://data.monarchinitiative.org/mappings/latest/umls_hp.sssom.tsv
  - dest: sssom/upheno-cross-species.sssom.tsv
    sources:
      - https://data.monarchinitiative.org/mappings/latest/upheno-cross-species.sssom.tsv
  - dest: sssom/upheno-species-independent.sssom.tsv
    sources:
      - https://data.monarchinitiative.org/mappings/latest/upheno-species-independent.sssom.tsv
  - dest: sssom/nbo-go.sssom.tsv
    sources:
      - https://data.monarchinitiative.org/mappings/latest/nbo-go.sssom.tsv
  - dest: sssom/uberon.sssom.tsv
    sources:
      - https://data.monarchinitiative.org/mappings/latest/uberon.sssom.tsv
  - dest: sssom/upheno-oba.sssom.tsv
    sources:
      - https://raw.githubusercontent.com/obophenotype/upheno-dev/refs/heads/master/src/mappings/upheno-oba.sssom.tsv
  - dest: sssom/mondo_hp_lexical.sssom.tsv
    sources:
      - https://raw.githubusercontent.com/mapping-commons/disease-mappings/refs/heads/main/mappings/mondo_hp_lexical.sssom.tsv
  - dest: sssom/mp_hp_mgi_all.sssom.tsv
    sources:
      - https://raw.githubusercontent.com/mapping-commons/mh_mapping_initiative/master/mappings/mp_hp_mgi_all.sssom.tsv
  - dest: sssom/oba-efo.sssom.tsv
    sources:
      - https://raw.githubusercontent.com/obophenotype/bio-attribute-ontology/master/src/mappings/oba-efo.sssom.tsv
  - dest: sssom/oba-vt.sssom.tsv
    sources:
      - https://raw.githubusercontent.com/obophenotype/bio-attribute-ontology/master/src/mappings/oba-vt.sssom.tsv
ingests:
  - globs: ["sssom/mp_hp_mgi_all.sssom.tsv"]
    command: '
      cat $GREBI_INGEST_FILENAME |
      sed "s/skos:exactMatch/semapv:crossSpeciesExactMatch/g" |
      grebi_ingest_sssom'
  - globs:
      - "sssom/gene_mappings.sssom.tsv"
      - "sssom/hp_mesh.sssom.tsv"
      - "sssom/mesh_chebi_biomappings.sssom.tsv"
      - "sssom/mondo.sssom.tsv"
      - "sssom/umls_hp.sssom.tsv"
      - "sssom/upheno-cross-species.sssom.tsv"
      - "sssom/upheno-species-independent.sssom.tsv"
      - "sssom/nbo-go.sssom.tsv"
      - "sssom/uberon.sssom.tsv"
      - "sssom/upheno-oba.sssom.tsv"
      - "sssom/mondo_hp_lexical.sssom.tsv"
      - "sssom/oba-efo.sssom.tsv"
      - "sssom/oba-vt.sssom.tsv"
    command: '
      cat $GREBI_INGEST_FILENAME |
      grebi_ingest_sssom'
