name: TestEdgeLinking
enabled: true
download:
  - dest: test_edge_linking/edges.jsonl
    sources:
      - tests/data/test_edge_linking/edges.jsonl
  - dest: test_edge_linking/nodes.jsonl
    sources:
      - tests/data/test_edge_linking/nodes.jsonl
ingests:
  - globs: ["test_edge_linking/edges.jsonl"]
    command: '
      cat $GREBI_INGEST_FILENAME |
      grebi_ingest_kgx_edges
          --kgx-inject-key-prefix test_el:'
  - globs: ["test_edge_linking/nodes.jsonl"]
    command: '
      cat $GREBI_INGEST_FILENAME |
      grebi_transform_jsonl
          --json-rename category:grebi:type
          --json-inject-key-prefix test_el:'
