name: TestCliqueMerge
enabled: true
ingests:
  - globs: ["dataload/00_fetch_data/test_clique_merge/edges.jsonl"]
    command: '
      grebi_ingest_kgx_edges
          --kgx-inject-key-prefix test_cm:'
  - globs: ["dataload/00_fetch_data/test_clique_merge/nodes.jsonl"]
    command: '
      grebi_transform_jsonl
          --json-rename category:grebi:type
          --json-inject-key-prefix test_cm:'
