name: UberGraph
enabled: true
download:
  - dest: ubergraph/ubergraph.nq.gz
    sources:
      - https://ubergraph.apps.renci.org/downloads/current/ubergraph.nq.gz
ingests:
  - globs: ["ubergraph/ubergraph.nq.gz"]
    memory: "32 GB"
    command: '
      zcat $GREBI_INGEST_FILENAME |
      grebi_rdf2jsonl
        --rdf-type rdf_quads_nq
        --rdf-graph "http://reasoner.renci.org/redundant"'
