id: UniProt
enabled: true
description: "The Universal Protein Resource providing comprehensive, high-quality protein sequence and functional annotation data"
download:
  - dest: uniprot/
    sources:
      - /nfs/production/parkinso/spot/jmcl/up/rdf/*.rdf.xz
ingests:
  - globs: ["uniprot/*.rdf.xz"]
    command: '
        xzcat $GREBI_INGEST_FILENAME |
        grebi_rdf2jsonl
            --rdf-type rdf_triples_xml
            --nest "http://purl.uniprot.org/core/attribution"
            --nest "http://purl.uniprot.org/core/recommendedName" 
            --nest "http://purl.uniprot.org/core/alternativeName" 
            --nest "http://purl.uniprot.org/core/locatedIn" 
            --p-to-ignore-o "http://purl.uniprot.org/core/annotation" 
            --p-to-ignore-o "http://purl.uniprot.org/core/sequence" 
            --p-to-ignore-o "http://purl.uniprot.org/core/range" 
            --p-to-ignore-o "http://biohackathon.org/resource/faldo#begin" 
            --p-to-ignore-o "http://biohackathon.org/resource/faldo#end"'
