[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:neo4j]
command=/opt/neo4j/bin/neo4j console
directory=/opt/neo4j
autostart=true
autorestart=true
startsecs=10
stdout_logfile=/var/log/supervisor/neo4j.log
stderr_logfile=/var/log/supervisor/neo4j_err.log
environment=NEO4J_HOME="/opt/neo4j"

[program:solr]
command=/opt/solr/bin/solr start -f -p 8983
directory=/opt/solr
autostart=true
autorestart=true
startsecs=10
stdout_logfile=/var/log/supervisor/solr.log
stderr_logfile=/var/log/supervisor/solr_err.log

[program:prefix_service]
command=/usr/local/bin/grebi_prefix_service
directory=/opt
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/prefix_service.log
stderr_logfile=/var/log/supervisor/prefix_service_err.log
environment=ROCKET_ADDRESS="0.0.0.0",ROCKET_PORT="8082",GREBI_PREFIX_MAP_PATH="/opt/grebi_prefix_maps/prefix_map_normalise.json"

[program:resolver_service]
command=java -jar /opt/grebi_resolver_service.jar
directory=/opt
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/resolver_service.log
stderr_logfile=/var/log/supervisor/resolver_service_err.log
environment=GREBI_SQLITE_SEARCH_PATH="/opt/grebi/data/sqlite"

[program:metadata_service]
command=java -jar /opt/grebi_metadata_service.jar
directory=/opt
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/metadata_service.log
stderr_logfile=/var/log/supervisor/metadata_service_err.log
environment=GREBI_METADATA_JSON_SEARCH_PATH="/opt/grebi/data/metadata"

[program:api]
command=java -jar /opt/grebi_api.jar
directory=/opt
autostart=true
autorestart=true
startsecs=30
stdout_logfile=/var/log/supervisor/api.log
stderr_logfile=/var/log/supervisor/api_err.log
environment=GREBI_NEO4J_HOST="bolt://localhost:7687/",GREBI_SOLR_HOST="http://localhost:8983/",GREBI_RESOLVER_HOST="http://localhost:8080/",GREBI_METADATA_HOST="http://localhost:8081/",GREBI_PREFIX_HOST="http://localhost:8082/"

[program:ui]
command=bash -c "cd /opt/grebi_ui && REACT_APP_APIURL=http://localhost:8090 REACT_APP_ENV=ebi PUBLIC_URL=/ npm run build && caddy run --config ./Caddyfile"
directory=/opt/grebi_ui
autostart=true
autorestart=true
startsecs=30
stdout_logfile=/var/log/supervisor/ui.log
stderr_logfile=/var/log/supervisor/ui_err.log
