services:
    grebi-ui:
      image: ghcr.io/ebispot/grebi_ui:dev
      ports:
        - 8080:8080
      environment:
        - PUBLIC_URL=/
        - REACT_APP_APIURL=http://localhost:8090
    grebi-api:
      image: ghcr.io/ebispot/grebi_api:dev
      ports:
        - 8090:8090
      depends_on:
        - grebi-neo4j
        - grebi-solr
        - grebi-resolver-service
        - grebi-metadata-service
      links:
        - grebi-neo4j
        - grebi-solr
        - grebi-resolver-service
        - grebi-metadata-service
      environment:
        - GREBI_NEO4J_HOST=bolt://grebi-neo4j:7687/
        - GREBI_SOLR_HOST=http://grebi-solr:8983/
        - GREBI_RESOLVER_HOST=http://grebi-resolver-service:8080/
        - GREBI_METADATA_HOST=http://grebi-metadata-service:8081/
    grebi-neo4j:
      image: neo4j:5.18.0
      ports:
        - 7474:7474
        - 7687:7687
      volumes:
        - ${GREBI_NEO_DATA_PATH:?Need path to Neo4j data folder}:/var/lib/neo4j/data
      environment:
        - NEO4J_AUTH=none
        - NEO4J_PLUGINS=["apoc"]
    grebi-solr:
      image: solr:9.5.0
      ports:
        - 8983:8983
      volumes:
        - ${GREBI_SOLR_PATH:?Need path to Solr data}:/var/solr/data
    grebi-resolver-service:
      image: ghcr.io/ebispot/grebi_resolver_service:dev
      ports:
        - 8080:8080
      volumes:
        - ${GREBI_SQLITE_SEARCH_PATH:?Need path to search for sqlite databases}:/sqlite
      environment:
        - GREBI_SQLITE_SEARCH_PATH=/sqlite
    grebi-metadata-service:
      image: ghcr.io/ebispot/grebi_metadata_service:dev
      ports:
        - 8081:8081
      volumes:
        - ${GREBI_METADATA_JSON_SEARCH_PATH:?Need path to search for metadata json files}:/metadata
      environment:
        - GREBI_METADATA_JSON_SEARCH_PATH=/metadata
volumes:
    grebi-neo4j-data:


