apiVersion: v1
kind: Service
metadata:
  name: grebi-resolver
  labels:
    app: grebi-resolver
spec:
  ports:
      - port: 8080
        targetPort: 8080
        name: http
        protocol: TCP
  selector:
    app: grebi-resolver
