apiVersion: v1
kind: Service
metadata:
  name: grebi-solr
  labels:
    app: grebi-solr
spec:
  ports:
      - port: 8983
        targetPort: 8983
        name: http
        protocol: TCP
  selector:
    app: grebi-solr