apiVersion: v1
kind: Service
metadata:
  name: grebi-neo4j
  labels:
    app: grebi-neo4j
spec:
  ports:
      - port: 7474
        targetPort: 7474
        name: http
        protocol: TCP
      - port: 7687
        targetPort: 7687
        name: bolt
        protocol: TCP
  selector:
    app: grebi-neo4j