id: OLS.ncit
enabled: true
description: "A reference terminology for cancer research and clinical care"
download:
  - dest: ols/ncit.json.gz
    sources:
      - /nfs/production/parkinso/spot/ols4/dev2/out/ontology_jsons/ncit.json.gz
      - https://ftp.ebi.ac.uk/pub/databases/spot/ols/dev/latest/ontology_jsons/ncit.json.gz
ingests:
  - globs: ["ols/ncit.json.gz"]
    command: '
      zcat $GREBI_INGEST_FILENAME |
      grebi_ingest_ols
        --ontologies ncit
        --skip-obsolete'