name: OLS.dcterms
enabled: true
download:
  - dest: ols/dcterms.json.gz
    sources:
      - /nfs/production/parkinso/spot/ols4/dev2/out/ontology_jsons/dcterms.json.gz
      - https://ftp.ebi.ac.uk/pub/databases/spot/ols/dev/latest/ontology_jsons/dcterms.json.gz
ingests:
  - globs: ["ols/dcterms.json.gz"]
    command: '
      zcat $GREBI_INGEST_FILENAME |
      grebi_ingest_ols
        --ontologies dcterms
        --skip-obsolete'