id: OLS.so
enabled: true
description: "A structured vocabulary for sequence annotation covering genomic feature types"
download:
  - dest: ols/so.json.gz
    sources:
      - /nfs/production/parkinso/spot/ols4/dev2/out/ontology_jsons/so.json.gz
      - https://ftp.ebi.ac.uk/pub/databases/spot/ols/dev/latest/ontology_jsons/so.json.gz
ingests:
  - globs: ["ols/so.json.gz"]
    command: '
      zcat $GREBI_INGEST_FILENAME |
      grebi_ingest_ols
        --ontologies so
        --skip-obsolete'