name: OLS.pato
enabled: true
download:
  - dest: ols/pato.json.gz
    sources:
      - /nfs/production/parkinso/spot/ols4/dev2/out/ontology_jsons/pato.json.gz
      - https://ftp.ebi.ac.uk/pub/databases/spot/ols/dev/latest/ontology_jsons/pato.json.gz
ingests:
  - globs: ["ols/pato.json.gz"]
    command: '
      zcat $GREBI_INGEST_FILENAME |
      grebi_ingest_ols
        --ontologies pato
        --skip-obsolete'