id: OLS.eco
enabled: true
description: "An ontology for representing types of evidence used in scientific assertions"
download:
  - dest: ols/eco.json.gz
    sources:
      - /nfs/production/parkinso/spot/ols4/dev2/out/ontology_jsons/eco.json.gz
      - https://ftp.ebi.ac.uk/pub/databases/spot/ols/dev/latest/ontology_jsons/eco.json.gz
ingests:
  - globs: ["ols/eco.json.gz"]
    command: '
      zcat $GREBI_INGEST_FILENAME |
      grebi_ingest_ols
        --ontologies eco
        --skip-obsolete'