name: OLS.cob
enabled: true
download:
  - dest: ols/cob.json.gz
    sources:
      - /nfs/production/parkinso/spot/ols4/dev-nextflow/out/ontology_jsons/cob.json.gz
      - https://ftp.ebi.ac.uk/pub/databases/spot/ols/dev/latest/ontology_jsons/cob.json.gz
ingests:
  - globs: ["ols/cob.json.gz"]
    command: '
      zcat $GREBI_INGEST_FILENAME |
      grebi_ingest_ols
        --ontologies cob
        --skip-obsolete'