id: OLS.iao
enabled: true
description: "An ontology of information entities such as documents, databases, and identifiers"
download:
  - dest: ols/iao.json.gz
    sources:
      - /nfs/production/parkinso/spot/ols4/dev2/out/ontology_jsons/iao.json.gz
      - https://ftp.ebi.ac.uk/pub/databases/spot/ols/dev/latest/ontology_jsons/iao.json.gz
ingests:
  - globs: ["ols/iao.json.gz"]
    command: '
      zcat $GREBI_INGEST_FILENAME |
      grebi_ingest_ols
        --ontologies iao
        --skip-obsolete'