id: OLS.go
enabled: true
description: "The comprehensive ontology of gene functions, biological processes, and cellular components"
download:
  - dest: ols/go.json.gz
    sources:
      - /nfs/production/parkinso/spot/ols4/dev2/out/ontology_jsons/go.json.gz
      - https://ftp.ebi.ac.uk/pub/databases/spot/ols/dev/latest/ontology_jsons/go.json.gz
ingests:
  - globs: ["ols/go.json.gz"]
    command: '
      zcat $GREBI_INGEST_FILENAME |
      grebi_ingest_ols
        --ontologies go
        --skip-obsolete'