name: OLS.upheno
enabled: true
download:
  - dest: ols/upheno.json.gz
    sources:
      - /nfs/production/parkinso/spot/ols4/dev-nextflow/out/ontology_jsons/upheno.json.gz
      - https://ftp.ebi.ac.uk/pub/databases/spot/ols/dev/latest/ontology_jsons/upheno.json.gz
ingests:
  - globs: ["ols/upheno.json.gz"]
    command: '
      zcat $GREBI_INGEST_FILENAME |
      grebi_ingest_ols
        --ontologies upheno
        --skip-obsolete'