id: OLS.oba
enabled: true
description: "An ontology of biological attributes covering organism-level traits and characteristics"
download:
  - dest: ols/oba.json.gz
    sources:
      - /nfs/production/parkinso/spot/ols4/dev2/out/ontology_jsons/oba.json.gz
      - https://ftp.ebi.ac.uk/pub/databases/spot/ols/dev/latest/ontology_jsons/oba.json.gz
ingests:
  - globs: ["ols/oba.json.gz"]
    command: '
      zcat $GREBI_INGEST_FILENAME |
      grebi_ingest_ols
        --ontologies oba
        --skip-obsolete'