
all: binding_nodes.jsonl.gz binding_edges.jsonl.gz cam_nodes.jsonl.gz cam_edges.jsonl.gz ctd_nodes.jsonl.gz ctd_edges.jsonl.gz drugcentral_nodes.jsonl.gz drugcentral_edges.jsonl.gz alliance_nodes.jsonl.gz alliance_edges.jsonl.gz gtex_nodes.jsonl.gz gtex_edges.jsonl.gz gtopdb_nodes.jsonl.gz gtopdb_edges.jsonl.gz hetionet_nodes.jsonl.gz hetionet_edges.jsonl.gz hgnc_nodes.jsonl.gz hgnc_edges.jsonl.gz hmdb_nodes.jsonl.gz hmdb_edges.jsonl.gz hgoa_nodes.jsonl.gz hgoa_edges.jsonl.gz icees_nodes.jsonl.gz icees_edges.jsonl.gz intact_nodes.jsonl.gz intact_edges.jsonl.gz panther_nodes.jsonl.gz panther_edges.jsonl.gz pharos_nodes.jsonl.gz pharos_edges.jsonl.gz string_nodes.jsonl.gz string_edges.jsonl.gz textmining_nodes.jsonl.gz textmining_edges.jsonl.gz viralproteome_nodes.jsonl.gz viralproteome_edges.jsonl.gz

binding_nodes.jsonl.gz:
	curl -L https://stars.renci.org/var/plater/bl-4.2.1/BINDING_Automat/9164067231dc9b8c/nodes.jsonl.gz > $@
binding_edges.jsonl.gz:
	curl -L https://stars.renci.org/var/plater/bl-4.2.1/BINDING_Automat/9164067231dc9b8c/edges.jsonl.gz > $@

cam_nodes.jsonl.gz:
	curl -L https://stars.renci.org/var/plater/bl-4.2.1/CAMKP_Automat/e92bd7b217535f2d/nodes.jsonl.gz > $@
cam_edges.jsonl.gz:
	curl -L https://stars.renci.org/var/plater/bl-4.2.1/CAMKP_Automat/e92bd7b217535f2d/edges.jsonl.gz > $@

ctd_nodes.jsonl.gz:
	curl -L https://stars.renci.org/var/plater/bl-4.2.1/CTD_Automat/f92c663160ec5e36/nodes.jsonl.gz > $@
ctd_edges.jsonl.gz:
	curl -L https://stars.renci.org/var/plater/bl-4.2.1/CTD_Automat/f92c663160ec5e36/edges.jsonl.gz  > $@

drugcentral_nodes.jsonl.gz:
	curl -L https://stars.renci.org/var/plater/bl-4.2.1/DrugCentral_Automat/dec0617490b49c7a/nodes.jsonl.gz > $@
drugcentral_edges.jsonl.gz:
	curl -L https://stars.renci.org/var/plater/bl-4.2.1/DrugCentral_Automat/dec0617490b49c7a/edges.jsonl.gz > $@

alliance_nodes.jsonl.gz:
	curl -L https://stars.renci.org/var/plater/bl-4.2.1/GenomeAllianceOrthologs_Automat/06e2a3c1eeea5251/nodes.jsonl.gz > $@
alliance_edges.jsonl.gz:
	curl -L https://stars.renci.org/var/plater/bl-4.2.1/GenomeAllianceOrthologs_Automat/06e2a3c1eeea5251/edges.jsonl.gz > $@

gtex_nodes.jsonl.gz:
	curl -L https://stars.renci.org/var/plater/bl-4.2.1/GTEx_Automat/a6448b9092bb81a1/nodes.jsonl.gz > $@
gtex_edges.jsonl.gz:
	curl -L https://stars.renci.org/var/plater/bl-4.2.1/GTEx_Automat/a6448b9092bb81a1/edges.jsonl.gz > $@

gtopdb_nodes.jsonl.gz:
	curl -L https://stars.renci.org/var/plater/bl-4.2.1/GtoPdb_Automat/0ea6074c824c2236/nodes.jsonl.gz > $@
gtopdb_edges.jsonl.gz:
	curl -L https://stars.renci.org/var/plater/bl-4.2.1/GtoPdb_Automat/0ea6074c824c2236/edges.jsonl.gz  > $@

hetionet_nodes.jsonl.gz:
	curl -L https://stars.renci.org/var/plater/bl-4.2.1/Hetio_Automat/85a5f53e63150e1e/nodes.jsonl.gz > $@
hetionet_edges.jsonl.gz:
	curl -L https://stars.renci.org/var/plater/bl-4.2.1/Hetio_Automat/85a5f53e63150e1e/edges.jsonl.gz > $@

hgnc_nodes.jsonl.gz:
	curl -L https://stars.renci.org/var/plater/bl-4.2.1/HGNC_Automat/dee31cfce74e5944/nodes.jsonl.gz > $@
hgnc_edges.jsonl.gz:
	curl -L https://stars.renci.org/var/plater/bl-4.2.1/HGNC_Automat/dee31cfce74e5944/edges.jsonl.gz > $@

hmdb_nodes.jsonl.gz:
	curl -L https://stars.renci.org/var/plater/bl-4.2.1/HMDB_Automat/6715124699b6dbf0/nodes.jsonl.gz > $@
hmdb_edges.jsonl.gz:
	curl -L https://stars.renci.org/var/plater/bl-4.2.1/HMDB_Automat/6715124699b6dbf0/edges.jsonl.gz > $@

hgoa_nodes.jsonl.gz:
	curl -L https://stars.renci.org/var/plater/bl-4.2.1/HumanGOA_Automat/06f107a4e9e8e547/nodes.jsonl.gz > $@
hgoa_edges.jsonl.gz:
	curl -L https://stars.renci.org/var/plater/bl-4.2.1/HumanGOA_Automat/06f107a4e9e8e547/edges.jsonl.gz > $@

icees_nodes.jsonl.gz:
	curl -L https://stars.renci.org/var/plater/bl-4.2.1/icees-kg/1.5.0/nodes.jsonl.gz > $@
icees_edges.jsonl.gz:
	curl -L https://stars.renci.org/var/plater/bl-4.2.1/icees-kg/1.5.0/edges.jsonl.gz > $@

intact_nodes.jsonl.gz:
	curl -L https://stars.renci.org/var/plater/bl-4.2.1/IntAct_Automat/e5b936f966a02c2c/nodes.jsonl.gz > $@
intact_edges.jsonl.gz:
	curl -L https://stars.renci.org/var/plater/bl-4.2.1/IntAct_Automat/e5b936f966a02c2c/edges.jsonl.gz > $@

panther_nodes.jsonl.gz:
	curl -L https://stars.renci.org/var/plater/bl-4.2.1/PANTHER_Automat/c0189f14ba41da6c/nodes.jsonl.gz > $@
panther_edges.jsonl.gz:
	curl -L https://stars.renci.org/var/plater/bl-4.2.1/PANTHER_Automat/c0189f14ba41da6c/edges.jsonl.gz > $@

pharos_nodes.jsonl.gz:
	curl -L https://stars.renci.org/var/plater/bl-4.2.1/PHAROS_Automat/d3068b509bf17ff3/nodes.jsonl.gz > $@
pharos_edges.jsonl.gz:
	curl -L https://stars.renci.org/var/plater/bl-4.2.1/PHAROS_Automat/d3068b509bf17ff3/edges.jsonl.gz > $@

string_nodes.jsonl.gz:
	curl -L https://stars.renci.org/var/plater/bl-4.2.1/STRING-DB_Automat/4ca5a0ce557e2c18/nodes.jsonl.gz > $@
string_edges.jsonl.gz:
	curl -L https://stars.renci.org/var/plater/bl-4.2.1/STRING-DB_Automat/4ca5a0ce557e2c18/edges.jsonl.gz > $@

textmining_nodes.jsonl.gz:
	curl -L https://stars.renci.org/var/plater/bl-4.2.1/TMKP_Automat/2ae17047aa1b5f3c/nodes.jsonl.gz > $@
textmining_edges.jsonl.gz:
	curl -L https://stars.renci.org/var/plater/bl-4.2.1/TMKP_Automat/2ae17047aa1b5f3c/edges.jsonl.gz > $@

viralproteome_nodes.jsonl.gz:
	curl -L https://stars.renci.org/var/plater/bl-4.2.1/ViralProteome_Automat/8ca116ae0bba6945/nodes.jsonl.gz > $@
viralproteome_edges.jsonl.gz:
	curl -L https://stars.renci.org/var/plater/bl-4.2.1/ViralProteome_Automat/8ca116ae0bba6945/edges.jsonl.gz > $@

.PHONY: all


