name: Test dataload 

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Test dataload
        run: GREBI_SUBGRAPH=hello_world ./dataload/scripts/dataload_local.sh
